// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: rpcpb/services.proto

package rpcpb

import (
	clientpb "github.com/leonidas-c2/leonidas/protobuf/clientpb"
	commonpb "github.com/leonidas-c2/leonidas/protobuf/commonpb"
	leonidaspb "github.com/leonidas-c2/leonidas/protobuf/leonidaspb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_rpcpb_services_proto protoreflect.FileDescriptor

const file_rpcpb_services_proto_rawDesc = "" +
	"\n\x14rpcpb/services.proto\x12\x05rpcpb\x1a\x15commonpb/common.proto\x1a\x19" +
	"leonidaspb/leonidas.proto\x1a\x15clientpb/client.proto2\xbe_\n\x0bLeonidasRP" +
	"C\x120\n\nGetVersion\x12\x0f.commonpb.Empty\x1a\x11.clientpb.Version\x127\n" +
	"\tClientLog\x12\x17.clientpb.ClientLogData\x1a\x0f.commonpb.Empty(\x01\x124" +
	"\n\x0cGetOperators\x12\x0f.commonpb.Empty\x1a\x13.clientpb.Operators\x12,\n" +
	"\x04Kill\x12\x13.leonidaspb.KillReq\x1a\x0f.commonpb.Empty\x12B\n\x0bReconfi" +
	"gure\x12\x1a.leonidaspb.ReconfigureReq\x1a\x17.leonidaspb.Reconfigure\x12.\n" +
	"\x06Rename\x12\x13.clientpb.RenameReq\x1a\x0f.commonpb.Empty\x122\n\x0bGetSe" +
	"ssions\x12\x0f.commonpb.Empty\x1a\x12.clientpb.Sessions\x123\n\x0cMonitorSta" +
	"rt\x12\x0f.commonpb.Empty\x1a\x12.commonpb.Response\x12/\n\x0bMonitorStop" +
	"\x12\x0f.commonpb.Empty\x1a\x0f.commonpb.Empty\x12C\n\x11MonitorListConfi" +
	"g\x12\x0f.commonpb.Empty\x1a\x1d.clientpb.MonitoringProviders\x12D\n\x10Moni" +
	"torAddConfig\x12\x1c.clientpb.MonitoringProvider\x1a\x12.commonpb.Respons" +
	"e\x12D\n\x10MonitorDelConfig\x12\x1c.clientpb.MonitoringProvider\x1a\x12.com" +
	"monpb.Response\x12>\n\x0eGetAIProviders\x12\x0f.commonpb.Empty\x1a\x1b.clien" +
	"tpb.AIProviderConfigs\x12@\n\x12GetAIConversations\x12\x0f.commonpb.Empty" +
	"\x1a\x19.clientpb.AIConversations\x12J\n\x11GetAIConversation\x12\x1b.client" +
	"pb.AIConversationReq\x1a\x18.clientpb.AIConversation\x12H\n\x12SaveAIConvers" +
	"ation\x12\x18.clientpb.AIConversation\x1a\x18.clientpb.AIConversation\x12D\n" +
	"\x14DeleteAIConversation\x12\x1b.clientpb.AIConversationReq\x1a\x0f.commonpb" +
	".Empty\x12Z\n\x19GetAIConversationMessages\x12\x1b.clientpb.AIConversationRe" +
	"q\x1a .clientpb.AIConversationMessages\x12]\n\x19SaveAIConversationMessag" +
	"e\x12\x1f.clientpb.AIConversationMessage\x1a\x1f.clientpb.AIConversationMess" +
	"age\x12E\n\x11StartMTLSListener\x12\x19.clientpb.MTLSListenerReq\x1a\x15.cli" +
	"entpb.ListenerJob\x12A\n\x0fStartWGListener\x12\x17.clientpb.WGListenerRe" +
	"q\x1a\x15.clientpb.ListenerJob\x12C\n\x10StartDNSListener\x12\x18.clientpb.D" +
	"NSListenerReq\x1a\x15.clientpb.ListenerJob\x12F\n\x12StartHTTPSListener\x12" +
	"\x19.clientpb.HTTPListenerReq\x1a\x15.clientpb.ListenerJob\x12E\n\x11StartHT" +
	"TPListener\x12\x19.clientpb.HTTPListenerReq\x1a\x15.clientpb.ListenerJob\x12" +
	"0\n\nGetBeacons\x12\x0f.commonpb.Empty\x1a\x11.clientpb.Beacons\x12/\n\tGetB" +
	"eacon\x12\x10.clientpb.Beacon\x1a\x10.clientpb.Beacon\x12-\n\x08RmBeacon\x12" +
	"\x10.clientpb.Beacon\x1a\x0f.commonpb.Empty\x129\n\x0eGetBeaconTasks\x12\x10" +
	".clientpb.Beacon\x1a\x15.clientpb.BeaconTasks\x12B\n\x14GetBeaconTaskContent" +
	"\x12\x14.clientpb.BeaconTask\x1a\x14.clientpb.BeaconTask\x12>\n\x10CancelBea" +
	"conTask\x12\x14.clientpb.BeaconTask\x1a\x14.clientpb.BeaconTask\x12N\n Updat" +
	"eBeaconIntegrityInformation\x12\x19.clientpb.BeaconIntegrity\x1a\x0f.commonp" +
	"b.Empty\x12*\n\x07GetJobs\x12\x0f.commonpb.Empty\x1a\x0e.clientpb.Jobs\x122" +
	"\n\x07KillJob\x12\x14.clientpb.KillJobReq\x1a\x11.clientpb.KillJob\x127\n" +
	"\x0bRestartJobs\x12\x17.clientpb.RestartJobReq\x1a\x0f.commonpb.Empty\x12O\n" +
	"\x16StartTCPStagerListener\x12\x1b.clientpb.StagerListenerReq\x1a\x18.client" +
	"pb.StagerListener\x12)\n\x07LootAdd\x12\x0e.clientpb.Loot\x1a\x0e.clientpb.L" +
	"oot\x12)\n\x06LootRm\x12\x0e.clientpb.Loot\x1a\x0f.commonpb.Empty\x12,\n\nLo" +
	"otUpdate\x12\x0e.clientpb.Loot\x1a\x0e.clientpb.Loot\x12-\n\x0bLootConten" +
	"t\x12\x0e.clientpb.Loot\x1a\x0e.clientpb.Loot\x12-\n\x07LootAll\x12\x0f.comm" +
	"onpb.Empty\x1a\x11.clientpb.AllLoot\x12/\n\x05Creds\x12\x0f.commonpb.Empt" +
	"y\x1a\x15.clientpb.Credentials\x122\n\x08CredsAdd\x12\x15.clientpb.Credentia" +
	"ls\x1a\x0f.commonpb.Empty\x121\n\x07CredsRm\x12\x15.clientpb.Credentials\x1a" +
	"\x0f.commonpb.Empty\x125\n\x0bCredsUpdate\x12\x15.clientpb.Credentials" +
	"\x1a\x0f.commonpb.Empty\x129\n\x0bGetCredByID\x12\x14.clientpb.Credential" +
	"\x1a\x14.clientpb.Credential\x12A\n\x12GetCredsByHashType\x12\x14.clientpb.C" +
	"redential\x1a\x15.clientpb.Credentials\x12J\n\x1bGetPlaintextCredsByHashType" +
	"\x12\x14.clientpb.Credential\x1a\x15.clientpb.Credentials\x12@\n\x12CredsSni" +
	"ffHashType\x12\x14.clientpb.Credential\x1a\x14.clientpb.Credential\x12,\n" +
	"\x05Hosts\x12\x0f.commonpb.Empty\x1a\x12.clientpb.AllHosts\x12&\n\x04Host" +
	"\x12\x0e.clientpb.Host\x1a\x0e.clientpb.Host\x12)\n\x06HostRm\x12\x0e.client" +
	"pb.Host\x1a\x0f.commonpb.Empty\x12+\n\tHostIOCRm\x12\r.clientpb.IOC\x1a\x0f." +
	"commonpb.Empty\x125\n\x08Generate\x12\x15.clientpb.GenerateReq\x1a\x12.clien" +
	"tpb.Generate\x12L\n\x15GenerateSpoofMetadata\x12\".clientpb.GenerateSpoofMet" +
	"adataReq\x1a\x0f.commonpb.Empty\x12R\n\x10GenerateExternal\x12\x1d.clientpb." +
	"ExternalGenerateReq\x1a\x1f.clientpb.ExternalImplantConfig\x12M\n\x19Generat" +
	"eExternalSaveBuild\x12\x1f.clientpb.ExternalImplantBinary\x1a\x0f.commonpb.E" +
	"mpty\x12Y\n\x1eGenerateExternalGetBuildConfig\x12\x16.clientpb.ImplantBuild" +
	"\x1a\x1f.clientpb.ExternalImplantConfig\x12?\n\rGenerateStage\x12\x1a.client" +
	"pb.GenerateStageReq\x1a\x12.clientpb.Generate\x12?\n\x11StageImplantBuild" +
	"\x12\x19.clientpb.ImplantStageReq\x1a\x0f.commonpb.Empty\x12=\n\x11GetHTTPC2" +
	"Profiles\x12\x0f.commonpb.Empty\x1a\x17.clientpb.HTTPC2Configs\x12H\n\x16Get" +
	"HTTPC2ProfileByName\x12\x16.clientpb.C2ProfileReq\x1a\x16.clientpb.HTTPC2Con" +
	"fig\x12?\n\x11SaveHTTPC2Profile\x12\x19.clientpb.HTTPC2ConfigReq\x1a\x0f.com" +
	"monpb.Empty\x127\n\x0fBuilderRegister\x12\x11.clientpb.Builder\x1a\x0f.clien" +
	"tpb.Event0\x01\x122\n\x0eBuilderTrigger\x12\x0f.clientpb.Event\x1a\x0f.commo" +
	"npb.Empty\x12/\n\x08Builders\x12\x0f.commonpb.Empty\x1a\x12.clientpb.Builder" +
	"s\x12J\n\x12GetCertificateInfo\x12\x19.clientpb.CertificatesReq\x1a\x19.clie" +
	"ntpb.CertificateInfo\x12R\n\x1bGetCertificateAuthorityInfo\x12\x0f.commonpb." +
	"Empty\x1a\".clientpb.CertificateAuthorityInfo\x128\n\x05Crack\x12\x16.client" +
	"pb.CrackCommand\x1a\x17.clientpb.CrackResponse\x12A\n\x14CrackstationRegiste" +
	"r\x12\x16.clientpb.Crackstation\x1a\x0f.clientpb.Event0\x01\x127\n\x13Cracks" +
	"tationTrigger\x12\x0f.clientpb.Event\x1a\x0f.commonpb.Empty\x12B\n\x15Cracks" +
	"tationBenchmark\x12\x18.clientpb.CrackBenchmark\x1a\x0f.commonpb.Empty\x129" +
	"\n\rCrackstations\x12\x0f.commonpb.Empty\x1a\x17.clientpb.Crackstations\x129" +
	"\n\rCrackTaskByID\x12\x13.clientpb.CrackTask\x1a\x13.clientpb.CrackTask\x127" +
	"\n\x0fCrackTaskUpdate\x12\x13.clientpb.CrackTask\x1a\x0f.commonpb.Empty\x12;" +
	"\n\x0eCrackFilesList\x12\x13.clientpb.CrackFile\x1a\x14.clientpb.CrackFiles" +
	"\x12;\n\x0fCrackFileCreate\x12\x13.clientpb.CrackFile\x1a\x13.clientpb.Crack" +
	"File\x12A\n\x14CrackFileChunkUpload\x12\x18.clientpb.CrackFileChunk\x1a\x0f." +
	"commonpb.Empty\x12L\n\x16CrackFileChunkDownload\x12\x18.clientpb.CrackFileCh" +
	"unk\x1a\x18.clientpb.CrackFileChunk\x129\n\x11CrackFileComplete\x12\x13.clie" +
	"ntpb.CrackFile\x1a\x0f.commonpb.Empty\x127\n\x0fCrackFileDelete\x12\x13.clie" +
	"ntpb.CrackFile\x1a\x0f.commonpb.Empty\x129\n\nRegenerate\x12\x17.clientpb.Re" +
	"generateReq\x1a\x12.clientpb.Generate\x129\n\rImplantBuilds\x12\x0f.commonpb" +
	".Empty\x1a\x17.clientpb.ImplantBuilds\x12:\n\x12DeleteImplantBuild\x12\x13.c" +
	"lientpb.DeleteReq\x1a\x0f.commonpb.Empty\x12/\n\x08Canaries\x12\x0f.commonpb" +
	".Empty\x1a\x12.clientpb.Canaries\x12C\n\x16GenerateWGClientConfig\x12\x0f.co" +
	"mmonpb.Empty\x1a\x18.clientpb.WGClientConfig\x129\n\x10GenerateUniqueIP\x12" +
	"\x0f.commonpb.Empty\x1a\x14.clientpb.UniqueWGIP\x12=\n\x0fImplantProfiles" +
	"\x12\x0f.commonpb.Empty\x1a\x19.clientpb.ImplantProfiles\x12<\n\x14DeleteImp" +
	"lantProfile\x12\x13.clientpb.DeleteReq\x1a\x0f.commonpb.Empty\x12H\n\x12Save" +
	"ImplantProfile\x12\x18.clientpb.ImplantProfile\x1a\x18.clientpb.ImplantProfi" +
	"le\x12A\n\x0cShellcodeRDI\x12\x19.clientpb.ShellcodeRDIReq\x1a\x16.clientpb." +
	"ShellcodeRDI\x122\n\x0bGetCompiler\x12\x0f.commonpb.Empty\x1a\x12.clientpb.C" +
	"ompiler\x12K\n\x10ShellcodeEncoder\x12\x1c.clientpb.ShellcodeEncodeReq" +
	"\x1a\x19.clientpb.ShellcodeEncode\x12E\n\x13ShellcodeEncoderMap\x12\x0f.comm" +
	"onpb.Empty\x1a\x1d.clientpb.ShellcodeEncoderMap\x12A\n\x11TrafficEncoderMap" +
	"\x12\x0f.commonpb.Empty\x1a\x1b.clientpb.TrafficEncoderMap\x12L\n\x11Traffic" +
	"EncoderAdd\x12\x18.clientpb.TrafficEncoder\x1a\x1d.clientpb.TrafficEncoderTe" +
	"sts\x12=\n\x10TrafficEncoderRm\x12\x18.clientpb.TrafficEncoder\x1a\x0f.commo" +
	"npb.Empty\x12/\n\x08Websites\x12\x0f.commonpb.Empty\x1a\x12.clientpb.Website" +
	"s\x12/\n\x07Website\x12\x11.clientpb.Website\x1a\x11.clientpb.Website\x123\n" +
	"\rWebsiteRemove\x12\x11.clientpb.Website\x1a\x0f.commonpb.Empty\x12C\n\x11We" +
	"bsiteAddContent\x12\x1b.clientpb.WebsiteAddContent\x1a\x11.clientpb.Website" +
	"\x12F\n\x14WebsiteUpdateContent\x12\x1b.clientpb.WebsiteAddContent\x1a\x11.c" +
	"lientpb.Website\x12I\n\x14WebsiteRemoveContent\x12\x1e.clientpb.WebsiteRemov" +
	"eContent\x1a\x11.clientpb.Website\x12*\n\x04Ping\x12\x10.leonidaspb.Ping\x1a" +
	"\x10.leonidaspb.Ping\x12'\n\x02Ps\x12\x11.leonidaspb.PsReq\x1a\x0e.leonidasp" +
	"b.Ps\x12<\n\tTerminate\x12\x18.leonidaspb.TerminateReq\x1a\x15.leonidaspb.Te" +
	"rminate\x129\n\x08Ifconfig\x12\x17.leonidaspb.IfconfigReq\x1a\x14.leonidaspb" +
	".Ifconfig\x126\n\x07Netstat\x12\x16.leonidaspb.NetstatReq\x1a\x13.leonidaspb" +
	".Netstat\x12'\n\x02Ls\x12\x11.leonidaspb.LsReq\x1a\x0e.leonidaspb.Ls\x12(\n" +
	"\x02Cd\x12\x11.leonidaspb.CdReq\x1a\x0f.leonidaspb.Pwd\x12*\n\x03Pwd\x12\x12" +
	".leonidaspb.PwdReq\x1a\x0f.leonidaspb.Pwd\x12'\n\x02Mv\x12\x11.leonidaspb.Mv" +
	"Req\x1a\x0e.leonidaspb.Mv\x12'\n\x02Cp\x12\x11.leonidaspb.CpReq\x1a\x0e.leon" +
	"idaspb.Cp\x12'\n\x02Rm\x12\x11.leonidaspb.RmReq\x1a\x0e.leonidaspb.Rm\x120\n" +
	"\x05Mkdir\x12\x14.leonidaspb.MkdirReq\x1a\x11.leonidaspb.Mkdir\x129\n\x08Dow" +
	"nload\x12\x17.leonidaspb.DownloadReq\x1a\x14.leonidaspb.Download\x123\n\x06U" +
	"pload\x12\x15.leonidaspb.UploadReq\x1a\x12.leonidaspb.Upload\x12-\n\x04Grep" +
	"\x12\x13.leonidaspb.GrepReq\x1a\x10.leonidaspb.Grep\x120\n\x05Chmod\x12\x14." +
	"leonidaspb.ChmodReq\x1a\x11.leonidaspb.Chmod\x120\n\x05Chown\x12\x14.leonida" +
	"spb.ChownReq\x1a\x11.leonidaspb.Chown\x126\n\x07Chtimes\x12\x16.leonidaspb.C" +
	"htimesReq\x1a\x13.leonidaspb.Chtimes\x12;\n\x0cMemfilesList\x12\x1b.leonidas" +
	"pb.MemfilesListReq\x1a\x0e.leonidaspb.Ls\x12B\n\x0bMemfilesAdd\x12\x1a.leoni" +
	"daspb.MemfilesAddReq\x1a\x17.leonidaspb.MemfilesAdd\x12?\n\nMemfilesRm" +
	"\x12\x19.leonidaspb.MemfilesRmReq\x1a\x16.leonidaspb.MemfilesRm\x120\n\x05Mo" +
	"unt\x12\x14.leonidaspb.MountReq\x1a\x11.leonidaspb.Mount\x12B\n\x0bProcessDu" +
	"mp\x12\x1a.leonidaspb.ProcessDumpReq\x1a\x17.leonidaspb.ProcessDump\x120" +
	"\n\x05RunAs\x12\x14.leonidaspb.RunAsReq\x1a\x11.leonidaspb.RunAs\x12B\n\x0bI" +
	"mpersonate\x12\x1a.leonidaspb.ImpersonateReq\x1a\x17.leonidaspb.Impersonate" +
	"\x12<\n\tRevToSelf\x12\x18.leonidaspb.RevToSelfReq\x1a\x15.leonidaspb.RevToS" +
	"elf\x12:\n\tGetSystem\x12\x16.clientpb.GetSystemReq\x1a\x15.leonidaspb.GetSy" +
	"stem\x12-\n\x04Task\x12\x13.leonidaspb.TaskReq\x1a\x10.leonidaspb.Task\x12)" +
	"\n\x03Msf\x12\x10.clientpb.MSFReq\x1a\x10.leonidaspb.Task\x125\n\tMsfRemote" +
	"\x12\x16.clientpb.MSFRemoteReq\x1a\x10.leonidaspb.Task\x12N\n\x0fExecuteAsse" +
	"mbly\x12\x1e.leonidaspb.ExecuteAssemblyReq\x1a\x1b.leonidaspb.ExecuteAssembl" +
	"y\x124\n\x07Migrate\x12\x14.clientpb.MigrateReq\x1a\x13.leonidaspb.Migrat" +
	"e\x126\n\x07Execute\x12\x16.leonidaspb.ExecuteReq\x1a\x13.leonidaspb.Execute" +
	"\x12D\n\x0eExecuteWindows\x12\x1d.leonidaspb.ExecuteWindowsReq\x1a\x13.leoni" +
	"daspb.Execute\x12N\n\x0fExecuteChildren\x12\x1e.leonidaspb.ExecuteChildrenRe" +
	"q\x1a\x1b.leonidaspb.ExecuteChildren\x129\n\x08Sideload\x12\x17.leonidaspb.S" +
	"ideloadReq\x1a\x14.leonidaspb.Sideload\x12?\n\x08SpawnDll\x12\x1d.leonidaspb" +
	".InvokeSpawnDllReq\x1a\x14.leonidaspb.SpawnDll\x12?\n\nScreenshot\x12\x19.le" +
	"onidaspb.ScreenshotReq\x1a\x16.leonidaspb.Screenshot\x12T\n\x11CurrentTokenO" +
	"wner\x12 .leonidaspb.CurrentTokenOwnerReq\x1a\x1d.leonidaspb.CurrentTokenOwn" +
	"er\x129\n\x08Services\x12\x17.leonidaspb.ServicesReq\x1a\x14.leonidaspb.Serv" +
	"ices\x12H\n\rServiceDetail\x12\x1c.leonidaspb.ServiceDetailReq\x1a\x19.leoni" +
	"daspb.ServiceDetail\x12P\n\x12StartServiceByName\x12!.leonidaspb.StartServic" +
	"eByNameReq\x1a\x17.leonidaspb.ServiceInfo\x12R\n\x12PivotStartListener\x12!." +
	"leonidaspb.PivotStartListenerReq\x1a\x19.leonidaspb.PivotListener\x12F\n\x11" +
	"PivotStopListener\x12 .leonidaspb.PivotStopListenerReq\x1a\x0f.commonpb.Empt" +
	"y\x12R\n\x15PivotSessionListeners\x12\x1d.leonidaspb.PivotListenersReq" +
	"\x1a\x1a.leonidaspb.PivotListeners\x123\n\nPivotGraph\x12\x0f.commonpb.Empty" +
	"\x1a\x14.clientpb.PivotGraph\x12D\n\x0cStartService\x12\x1b.leonidaspb.Start" +
	"ServiceReq\x1a\x17.leonidaspb.ServiceInfo\x12B\n\x0bStopService\x12\x1a.leon" +
	"idaspb.StopServiceReq\x1a\x17.leonidaspb.ServiceInfo\x12F\n\rRemoveServic" +
	"e\x12\x1c.leonidaspb.RemoveServiceReq\x1a\x17.leonidaspb.ServiceInfo\x12<\n" +
	"\tMakeToken\x12\x18.leonidaspb.MakeTokenReq\x1a\x15.leonidaspb.MakeToken\x12" +
	"1\n\x06GetEnv\x12\x12.leonidaspb.EnvReq\x1a\x13.leonidaspb.EnvInfo\x123\n" +
	"\x06SetEnv\x12\x15.leonidaspb.SetEnvReq\x1a\x12.leonidaspb.SetEnv\x129\n\x08" +
	"UnsetEnv\x12\x17.leonidaspb.UnsetEnvReq\x1a\x14.leonidaspb.UnsetEnv\x125" +
	"\n\x08Backdoor\x12\x15.clientpb.BackdoorReq\x1a\x12.clientpb.Backdoor\x12E\n" +
	"\x0cRegistryRead\x12\x1b.leonidaspb.RegistryReadReq\x1a\x18.leonidaspb.Regis" +
	"tryRead\x12H\n\rRegistryWrite\x12\x1c.leonidaspb.RegistryWriteReq\x1a\x19.le" +
	"onidaspb.RegistryWrite\x12T\n\x11RegistryCreateKey\x12 .leonidaspb.RegistryC" +
	"reateKeyReq\x1a\x1d.leonidaspb.RegistryCreateKey\x12T\n\x11RegistryDeleteKey" +
	"\x12 .leonidaspb.RegistryDeleteKeyReq\x1a\x1d.leonidaspb.RegistryDeleteKe" +
	"y\x12X\n\x13RegistryListSubKeys\x12!.leonidaspb.RegistrySubKeyListReq\x1a" +
	"\x1e.leonidaspb.RegistrySubKeyList\x12W\n\x12RegistryListValues\x12!.leonida" +
	"spb.RegistryListValuesReq\x1a\x1e.leonidaspb.RegistryValuesList\x12Q\n\x10Re" +
	"gistryReadHive\x12\x1f.leonidaspb.RegistryReadHiveReq\x1a\x1c.leonidaspb.Reg" +
	"istryReadHive\x12B\n\rRunSSHCommand\x12\x19.leonidaspb.SSHCommandReq\x1a\x16" +
	".leonidaspb.SSHCommand\x128\n\tHijackDLL\x12\x16.clientpb.DllHijackReq" +
	"\x1a\x13.clientpb.DllHijack\x129\n\x08GetPrivs\x12\x17.leonidaspb.GetPrivsRe" +
	"q\x1a\x14.leonidaspb.GetPrivs\x12[\n\x15StartRportFwdListener\x12$.leonidasp" +
	"b.RportFwdStartListenerReq\x1a\x1c.leonidaspb.RportFwdListener\x12W\n\x14Get" +
	"RportFwdListeners\x12 .leonidaspb.RportFwdListenersReq\x1a\x1d.leonidaspb.Rp" +
	"ortFwdListeners\x12Y\n\x14StopRportFwdListener\x12#.leonidaspb.RportFwdStopL" +
	"istenerReq\x1a\x1c.leonidaspb.RportFwdListener\x12?\n\x0bOpenSession\x12\x17" +
	".leonidaspb.OpenSession\x1a\x17.leonidaspb.OpenSession\x129\n\x0cCloseSessio" +
	"n\x12\x18.leonidaspb.CloseSession\x1a\x0f.commonpb.Empty\x12T\n\x11RegisterE" +
	"xtension\x12 .leonidaspb.RegisterExtensionReq\x1a\x1d.leonidaspb.RegisterExt" +
	"ension\x12H\n\rCallExtension\x12\x1c.leonidaspb.CallExtensionReq\x1a\x19.leo" +
	"nidaspb.CallExtension\x12K\n\x0eListExtensions\x12\x1d.leonidaspb.ListExtens" +
	"ionsReq\x1a\x1a.leonidaspb.ListExtensions\x12`\n\x15RegisterWasmExtension" +
	"\x12$.leonidaspb.RegisterWasmExtensionReq\x1a!.leonidaspb.RegisterWasmExtens" +
	"ion\x12W\n\x12ListWasmExtensions\x12!.leonidaspb.ListWasmExtensionsReq" +
	"\x1a\x1e.leonidaspb.ListWasmExtensions\x12T\n\x11ExecWasmExtension\x12 .leon" +
	"idaspb.ExecWasmExtensionReq\x1a\x1d.leonidaspb.ExecWasmExtension\x12R\n\x12W" +
	"GStartPortForward\x12!.leonidaspb.WGPortForwardStartReq\x1a\x19.leonidaspb.W" +
	"GPortForward\x12P\n\x11WGStopPortForward\x12 .leonidaspb.WGPortForwardStopRe" +
	"q\x1a\x19.leonidaspb.WGPortForward\x12@\n\x0cWGStartSocks\x12\x1b.leonidaspb" +
	".WGSocksStartReq\x1a\x13.leonidaspb.WGSocks\x12>\n\x0bWGStopSocks\x12\x1a.le" +
	"onidaspb.WGSocksStopReq\x1a\x13.leonidaspb.WGSocks\x12O\n\x10WGListForwarder" +
	"s\x12\x1e.leonidaspb.WGTCPForwardersReq\x1a\x1b.leonidaspb.WGTCPForwarder" +
	"s\x12O\n\x12WGListSocksServers\x12\x1d.leonidaspb.WGSocksServersReq\x1a\x1a." +
	"leonidaspb.WGSocksServers\x120\n\x05Shell\x12\x14.leonidaspb.ShellReq\x1a" +
	"\x11.leonidaspb.Shell\x12:\n\x0bShellResize\x12\x1a.leonidaspb.ShellResizeRe" +
	"q\x1a\x0f.commonpb.Empty\x126\n\x07Portfwd\x12\x16.leonidaspb.PortfwdReq\x1a" +
	"\x13.leonidaspb.Portfwd\x123\n\x0bCreateSocks\x12\x11.leonidaspb.Socks" +
	"\x1a\x11.leonidaspb.Socks\x120\n\nCloseSocks\x12\x11.leonidaspb.Socks\x1a" +
	"\x0f.commonpb.Empty\x12>\n\nSocksProxy\x12\x15.leonidaspb.SocksData\x1a\x15." +
	"leonidaspb.SocksData(\x010\x01\x126\n\x0cCreateTunnel\x12\x12.leonidaspb.Tun" +
	"nel\x1a\x12.leonidaspb.Tunnel\x122\n\x0bCloseTunnel\x12\x12.leonidaspb.Tunne" +
	"l\x1a\x0f.commonpb.Empty\x12@\n\nTunnelData\x12\x16.leonidaspb.TunnelData" +
	"\x1a\x16.leonidaspb.TunnelData(\x010\x01\x12,\n\x06Events\x12\x0f.commonpb.E" +
	"mpty\x1a\x0f.clientpb.Event0\x01B0Z.github.com/leonidas-c2/leonidas/protobuf" +
	"/rpcpbb\x06proto3"

var file_rpcpb_services_proto_goTypes = []any{
	(*commonpb.Empty)(nil),                    // 0: commonpb.Empty
	(*clientpb.ClientLogData)(nil),            // 1: clientpb.ClientLogData
	(*leonidaspb.KillReq)(nil),                  // 2: leonidaspb.KillReq
	(*leonidaspb.ReconfigureReq)(nil),           // 3: leonidaspb.ReconfigureReq
	(*clientpb.RenameReq)(nil),                // 4: clientpb.RenameReq
	(*clientpb.MonitoringProvider)(nil),       // 5: clientpb.MonitoringProvider
	(*clientpb.AIConversationReq)(nil),        // 6: clientpb.AIConversationReq
	(*clientpb.AIConversation)(nil),           // 7: clientpb.AIConversation
	(*clientpb.AIConversationMessage)(nil),    // 8: clientpb.AIConversationMessage
	(*clientpb.MTLSListenerReq)(nil),          // 9: clientpb.MTLSListenerReq
	(*clientpb.WGListenerReq)(nil),            // 10: clientpb.WGListenerReq
	(*clientpb.DNSListenerReq)(nil),           // 11: clientpb.DNSListenerReq
	(*clientpb.HTTPListenerReq)(nil),          // 12: clientpb.HTTPListenerReq
	(*clientpb.Beacon)(nil),                   // 13: clientpb.Beacon
	(*clientpb.BeaconTask)(nil),               // 14: clientpb.BeaconTask
	(*clientpb.BeaconIntegrity)(nil),          // 15: clientpb.BeaconIntegrity
	(*clientpb.KillJobReq)(nil),               // 16: clientpb.KillJobReq
	(*clientpb.RestartJobReq)(nil),            // 17: clientpb.RestartJobReq
	(*clientpb.StagerListenerReq)(nil),        // 18: clientpb.StagerListenerReq
	(*clientpb.Loot)(nil),                     // 19: clientpb.Loot
	(*clientpb.Credentials)(nil),              // 20: clientpb.Credentials
	(*clientpb.Credential)(nil),               // 21: clientpb.Credential
	(*clientpb.Host)(nil),                     // 22: clientpb.Host
	(*clientpb.IOC)(nil),                      // 23: clientpb.IOC
	(*clientpb.GenerateReq)(nil),              // 24: clientpb.GenerateReq
	(*clientpb.GenerateSpoofMetadataReq)(nil), // 25: clientpb.GenerateSpoofMetadataReq
	(*clientpb.ExternalGenerateReq)(nil),      // 26: clientpb.ExternalGenerateReq
	(*clientpb.ExternalImplantBinary)(nil),    // 27: clientpb.ExternalImplantBinary
	(*clientpb.ImplantBuild)(nil),             // 28: clientpb.ImplantBuild
	(*clientpb.GenerateStageReq)(nil),         // 29: clientpb.GenerateStageReq
	(*clientpb.ImplantStageReq)(nil),          // 30: clientpb.ImplantStageReq
	(*clientpb.C2ProfileReq)(nil),             // 31: clientpb.C2ProfileReq
	(*clientpb.HTTPC2ConfigReq)(nil),          // 32: clientpb.HTTPC2ConfigReq
	(*clientpb.Builder)(nil),                  // 33: clientpb.Builder
	(*clientpb.Event)(nil),                    // 34: clientpb.Event
	(*clientpb.CertificatesReq)(nil),          // 35: clientpb.CertificatesReq
	(*clientpb.CrackCommand)(nil),             // 36: clientpb.CrackCommand
	(*clientpb.Crackstation)(nil),             // 37: clientpb.Crackstation
	(*clientpb.CrackBenchmark)(nil),           // 38: clientpb.CrackBenchmark
	(*clientpb.CrackTask)(nil),                // 39: clientpb.CrackTask
	(*clientpb.CrackFile)(nil),                // 40: clientpb.CrackFile
	(*clientpb.CrackFileChunk)(nil),           // 41: clientpb.CrackFileChunk
	(*clientpb.RegenerateReq)(nil),            // 42: clientpb.RegenerateReq
	(*clientpb.DeleteReq)(nil),                // 43: clientpb.DeleteReq
	(*clientpb.ImplantProfile)(nil),           // 44: clientpb.ImplantProfile
	(*clientpb.ShellcodeRDIReq)(nil),          // 45: clientpb.ShellcodeRDIReq
	(*clientpb.ShellcodeEncodeReq)(nil),       // 46: clientpb.ShellcodeEncodeReq
	(*clientpb.TrafficEncoder)(nil),           // 47: clientpb.TrafficEncoder
	(*clientpb.Website)(nil),                  // 48: clientpb.Website
	(*clientpb.WebsiteAddContent)(nil),        // 49: clientpb.WebsiteAddContent
	(*clientpb.WebsiteRemoveContent)(nil),     // 50: clientpb.WebsiteRemoveContent
	(*leonidaspb.Ping)(nil),                     // 51: leonidaspb.Ping
	(*leonidaspb.PsReq)(nil),                    // 52: leonidaspb.PsReq
	(*leonidaspb.TerminateReq)(nil),             // 53: leonidaspb.TerminateReq
	(*leonidaspb.IfconfigReq)(nil),              // 54: leonidaspb.IfconfigReq
	(*leonidaspb.NetstatReq)(nil),               // 55: leonidaspb.NetstatReq
	(*leonidaspb.LsReq)(nil),                    // 56: leonidaspb.LsReq
	(*leonidaspb.CdReq)(nil),                    // 57: leonidaspb.CdReq
	(*leonidaspb.PwdReq)(nil),                   // 58: leonidaspb.PwdReq
	(*leonidaspb.MvReq)(nil),                    // 59: leonidaspb.MvReq
	(*leonidaspb.CpReq)(nil),                    // 60: leonidaspb.CpReq
	(*leonidaspb.RmReq)(nil),                    // 61: leonidaspb.RmReq
	(*leonidaspb.MkdirReq)(nil),                 // 62: leonidaspb.MkdirReq
	(*leonidaspb.DownloadReq)(nil),              // 63: leonidaspb.DownloadReq
	(*leonidaspb.UploadReq)(nil),                // 64: leonidaspb.UploadReq
	(*leonidaspb.GrepReq)(nil),                  // 65: leonidaspb.GrepReq
	(*leonidaspb.ChmodReq)(nil),                 // 66: leonidaspb.ChmodReq
	(*leonidaspb.ChownReq)(nil),                 // 67: leonidaspb.ChownReq
	(*leonidaspb.ChtimesReq)(nil),               // 68: leonidaspb.ChtimesReq
	(*leonidaspb.MemfilesListReq)(nil),          // 69: leonidaspb.MemfilesListReq
	(*leonidaspb.MemfilesAddReq)(nil),           // 70: leonidaspb.MemfilesAddReq
	(*leonidaspb.MemfilesRmReq)(nil),            // 71: leonidaspb.MemfilesRmReq
	(*leonidaspb.MountReq)(nil),                 // 72: leonidaspb.MountReq
	(*leonidaspb.ProcessDumpReq)(nil),           // 73: leonidaspb.ProcessDumpReq
	(*leonidaspb.RunAsReq)(nil),                 // 74: leonidaspb.RunAsReq
	(*leonidaspb.ImpersonateReq)(nil),           // 75: leonidaspb.ImpersonateReq
	(*leonidaspb.RevToSelfReq)(nil),             // 76: leonidaspb.RevToSelfReq
	(*clientpb.GetSystemReq)(nil),             // 77: clientpb.GetSystemReq
	(*leonidaspb.TaskReq)(nil),                  // 78: leonidaspb.TaskReq
	(*clientpb.MSFReq)(nil),                   // 79: clientpb.MSFReq
	(*clientpb.MSFRemoteReq)(nil),             // 80: clientpb.MSFRemoteReq
	(*leonidaspb.ExecuteAssemblyReq)(nil),       // 81: leonidaspb.ExecuteAssemblyReq
	(*clientpb.MigrateReq)(nil),               // 82: clientpb.MigrateReq
	(*leonidaspb.ExecuteReq)(nil),               // 83: leonidaspb.ExecuteReq
	(*leonidaspb.ExecuteWindowsReq)(nil),        // 84: leonidaspb.ExecuteWindowsReq
	(*leonidaspb.ExecuteChildrenReq)(nil),       // 85: leonidaspb.ExecuteChildrenReq
	(*leonidaspb.SideloadReq)(nil),              // 86: leonidaspb.SideloadReq
	(*leonidaspb.InvokeSpawnDllReq)(nil),        // 87: leonidaspb.InvokeSpawnDllReq
	(*leonidaspb.ScreenshotReq)(nil),            // 88: leonidaspb.ScreenshotReq
	(*leonidaspb.CurrentTokenOwnerReq)(nil),     // 89: leonidaspb.CurrentTokenOwnerReq
	(*leonidaspb.ServicesReq)(nil),              // 90: leonidaspb.ServicesReq
	(*leonidaspb.ServiceDetailReq)(nil),         // 91: leonidaspb.ServiceDetailReq
	(*leonidaspb.StartServiceByNameReq)(nil),    // 92: leonidaspb.StartServiceByNameReq
	(*leonidaspb.PivotStartListenerReq)(nil),    // 93: leonidaspb.PivotStartListenerReq
	(*leonidaspb.PivotStopListenerReq)(nil),     // 94: leonidaspb.PivotStopListenerReq
	(*leonidaspb.PivotListenersReq)(nil),        // 95: leonidaspb.PivotListenersReq
	(*leonidaspb.StartServiceReq)(nil),          // 96: leonidaspb.StartServiceReq
	(*leonidaspb.StopServiceReq)(nil),           // 97: leonidaspb.StopServiceReq
	(*leonidaspb.RemoveServiceReq)(nil),         // 98: leonidaspb.RemoveServiceReq
	(*leonidaspb.MakeTokenReq)(nil),             // 99: leonidaspb.MakeTokenReq
	(*leonidaspb.EnvReq)(nil),                   // 100: leonidaspb.EnvReq
	(*leonidaspb.SetEnvReq)(nil),                // 101: leonidaspb.SetEnvReq
	(*leonidaspb.UnsetEnvReq)(nil),              // 102: leonidaspb.UnsetEnvReq
	(*clientpb.BackdoorReq)(nil),              // 103: clientpb.BackdoorReq
	(*leonidaspb.RegistryReadReq)(nil),          // 104: leonidaspb.RegistryReadReq
	(*leonidaspb.RegistryWriteReq)(nil),         // 105: leonidaspb.RegistryWriteReq
	(*leonidaspb.RegistryCreateKeyReq)(nil),     // 106: leonidaspb.RegistryCreateKeyReq
	(*leonidaspb.RegistryDeleteKeyReq)(nil),     // 107: leonidaspb.RegistryDeleteKeyReq
	(*leonidaspb.RegistrySubKeyListReq)(nil),    // 108: leonidaspb.RegistrySubKeyListReq
	(*leonidaspb.RegistryListValuesReq)(nil),    // 109: leonidaspb.RegistryListValuesReq
	(*leonidaspb.RegistryReadHiveReq)(nil),      // 110: leonidaspb.RegistryReadHiveReq
	(*leonidaspb.SSHCommandReq)(nil),            // 111: leonidaspb.SSHCommandReq
	(*clientpb.DllHijackReq)(nil),             // 112: clientpb.DllHijackReq
	(*leonidaspb.GetPrivsReq)(nil),              // 113: leonidaspb.GetPrivsReq
	(*leonidaspb.RportFwdStartListenerReq)(nil), // 114: leonidaspb.RportFwdStartListenerReq
	(*leonidaspb.RportFwdListenersReq)(nil),     // 115: leonidaspb.RportFwdListenersReq
	(*leonidaspb.RportFwdStopListenerReq)(nil),  // 116: leonidaspb.RportFwdStopListenerReq
	(*leonidaspb.OpenSession)(nil),              // 117: leonidaspb.OpenSession
	(*leonidaspb.CloseSession)(nil),             // 118: leonidaspb.CloseSession
	(*leonidaspb.RegisterExtensionReq)(nil),     // 119: leonidaspb.RegisterExtensionReq
	(*leonidaspb.CallExtensionReq)(nil),         // 120: leonidaspb.CallExtensionReq
	(*leonidaspb.ListExtensionsReq)(nil),        // 121: leonidaspb.ListExtensionsReq
	(*leonidaspb.RegisterWasmExtensionReq)(nil), // 122: leonidaspb.RegisterWasmExtensionReq
	(*leonidaspb.ListWasmExtensionsReq)(nil),    // 123: leonidaspb.ListWasmExtensionsReq
	(*leonidaspb.ExecWasmExtensionReq)(nil),     // 124: leonidaspb.ExecWasmExtensionReq
	(*leonidaspb.WGPortForwardStartReq)(nil),    // 125: leonidaspb.WGPortForwardStartReq
	(*leonidaspb.WGPortForwardStopReq)(nil),     // 126: leonidaspb.WGPortForwardStopReq
	(*leonidaspb.WGSocksStartReq)(nil),          // 127: leonidaspb.WGSocksStartReq
	(*leonidaspb.WGSocksStopReq)(nil),           // 128: leonidaspb.WGSocksStopReq
	(*leonidaspb.WGTCPForwardersReq)(nil),       // 129: leonidaspb.WGTCPForwardersReq
	(*leonidaspb.WGSocksServersReq)(nil),        // 130: leonidaspb.WGSocksServersReq
	(*leonidaspb.ShellReq)(nil),                 // 131: leonidaspb.ShellReq
	(*leonidaspb.ShellResizeReq)(nil),           // 132: leonidaspb.ShellResizeReq
	(*leonidaspb.PortfwdReq)(nil),               // 133: leonidaspb.PortfwdReq
	(*leonidaspb.Socks)(nil),                    // 134: leonidaspb.Socks
	(*leonidaspb.SocksData)(nil),                // 135: leonidaspb.SocksData
	(*leonidaspb.Tunnel)(nil),                   // 136: leonidaspb.Tunnel
	(*leonidaspb.TunnelData)(nil),               // 137: leonidaspb.TunnelData
	(*clientpb.Version)(nil),                  // 138: clientpb.Version
	(*clientpb.Operators)(nil),                // 139: clientpb.Operators
	(*leonidaspb.Reconfigure)(nil),              // 140: leonidaspb.Reconfigure
	(*clientpb.Sessions)(nil),                 // 141: clientpb.Sessions
	(*commonpb.Response)(nil),                 // 142: commonpb.Response
	(*clientpb.MonitoringProviders)(nil),      // 143: clientpb.MonitoringProviders
	(*clientpb.AIProviderConfigs)(nil),        // 144: clientpb.AIProviderConfigs
	(*clientpb.AIConversations)(nil),          // 145: clientpb.AIConversations
	(*clientpb.AIConversationMessages)(nil),   // 146: clientpb.AIConversationMessages
	(*clientpb.ListenerJob)(nil),              // 147: clientpb.ListenerJob
	(*clientpb.Beacons)(nil),                  // 148: clientpb.Beacons
	(*clientpb.BeaconTasks)(nil),              // 149: clientpb.BeaconTasks
	(*clientpb.Jobs)(nil),                     // 150: clientpb.Jobs
	(*clientpb.KillJob)(nil),                  // 151: clientpb.KillJob
	(*clientpb.StagerListener)(nil),           // 152: clientpb.StagerListener
	(*clientpb.AllLoot)(nil),                  // 153: clientpb.AllLoot
	(*clientpb.AllHosts)(nil),                 // 154: clientpb.AllHosts
	(*clientpb.Generate)(nil),                 // 155: clientpb.Generate
	(*clientpb.ExternalImplantConfig)(nil),    // 156: clientpb.ExternalImplantConfig
	(*clientpb.HTTPC2Configs)(nil),            // 157: clientpb.HTTPC2Configs
	(*clientpb.HTTPC2Config)(nil),             // 158: clientpb.HTTPC2Config
	(*clientpb.Builders)(nil),                 // 159: clientpb.Builders
	(*clientpb.CertificateInfo)(nil),          // 160: clientpb.CertificateInfo
	(*clientpb.CertificateAuthorityInfo)(nil), // 161: clientpb.CertificateAuthorityInfo
	(*clientpb.CrackResponse)(nil),            // 162: clientpb.CrackResponse
	(*clientpb.Crackstations)(nil),            // 163: clientpb.Crackstations
	(*clientpb.CrackFiles)(nil),               // 164: clientpb.CrackFiles
	(*clientpb.ImplantBuilds)(nil),            // 165: clientpb.ImplantBuilds
	(*clientpb.Canaries)(nil),                 // 166: clientpb.Canaries
	(*clientpb.WGClientConfig)(nil),           // 167: clientpb.WGClientConfig
	(*clientpb.UniqueWGIP)(nil),               // 168: clientpb.UniqueWGIP
	(*clientpb.ImplantProfiles)(nil),          // 169: clientpb.ImplantProfiles
	(*clientpb.ShellcodeRDI)(nil),             // 170: clientpb.ShellcodeRDI
	(*clientpb.Compiler)(nil),                 // 171: clientpb.Compiler
	(*clientpb.ShellcodeEncode)(nil),          // 172: clientpb.ShellcodeEncode
	(*clientpb.ShellcodeEncoderMap)(nil),      // 173: clientpb.ShellcodeEncoderMap
	(*clientpb.TrafficEncoderMap)(nil),        // 174: clientpb.TrafficEncoderMap
	(*clientpb.TrafficEncoderTests)(nil),      // 175: clientpb.TrafficEncoderTests
	(*clientpb.Websites)(nil),                 // 176: clientpb.Websites
	(*leonidaspb.Ps)(nil),                       // 177: leonidaspb.Ps
	(*leonidaspb.Terminate)(nil),                // 178: leonidaspb.Terminate
	(*leonidaspb.Ifconfig)(nil),                 // 179: leonidaspb.Ifconfig
	(*leonidaspb.Netstat)(nil),                  // 180: leonidaspb.Netstat
	(*leonidaspb.Ls)(nil),                       // 181: leonidaspb.Ls
	(*leonidaspb.Pwd)(nil),                      // 182: leonidaspb.Pwd
	(*leonidaspb.Mv)(nil),                       // 183: leonidaspb.Mv
	(*leonidaspb.Cp)(nil),                       // 184: leonidaspb.Cp
	(*leonidaspb.Rm)(nil),                       // 185: leonidaspb.Rm
	(*leonidaspb.Mkdir)(nil),                    // 186: leonidaspb.Mkdir
	(*leonidaspb.Download)(nil),                 // 187: leonidaspb.Download
	(*leonidaspb.Upload)(nil),                   // 188: leonidaspb.Upload
	(*leonidaspb.Grep)(nil),                     // 189: leonidaspb.Grep
	(*leonidaspb.Chmod)(nil),                    // 190: leonidaspb.Chmod
	(*leonidaspb.Chown)(nil),                    // 191: leonidaspb.Chown
	(*leonidaspb.Chtimes)(nil),                  // 192: leonidaspb.Chtimes
	(*leonidaspb.MemfilesAdd)(nil),              // 193: leonidaspb.MemfilesAdd
	(*leonidaspb.MemfilesRm)(nil),               // 194: leonidaspb.MemfilesRm
	(*leonidaspb.Mount)(nil),                    // 195: leonidaspb.Mount
	(*leonidaspb.ProcessDump)(nil),              // 196: leonidaspb.ProcessDump
	(*leonidaspb.RunAs)(nil),                    // 197: leonidaspb.RunAs
	(*leonidaspb.Impersonate)(nil),              // 198: leonidaspb.Impersonate
	(*leonidaspb.RevToSelf)(nil),                // 199: leonidaspb.RevToSelf
	(*leonidaspb.GetSystem)(nil),                // 200: leonidaspb.GetSystem
	(*leonidaspb.Task)(nil),                     // 201: leonidaspb.Task
	(*leonidaspb.ExecuteAssembly)(nil),          // 202: leonidaspb.ExecuteAssembly
	(*leonidaspb.Migrate)(nil),                  // 203: leonidaspb.Migrate
	(*leonidaspb.Execute)(nil),                  // 204: leonidaspb.Execute
	(*leonidaspb.ExecuteChildren)(nil),          // 205: leonidaspb.ExecuteChildren
	(*leonidaspb.Sideload)(nil),                 // 206: leonidaspb.Sideload
	(*leonidaspb.SpawnDll)(nil),                 // 207: leonidaspb.SpawnDll
	(*leonidaspb.Screenshot)(nil),               // 208: leonidaspb.Screenshot
	(*leonidaspb.CurrentTokenOwner)(nil),        // 209: leonidaspb.CurrentTokenOwner
	(*leonidaspb.Services)(nil),                 // 210: leonidaspb.Services
	(*leonidaspb.ServiceDetail)(nil),            // 211: leonidaspb.ServiceDetail
	(*leonidaspb.ServiceInfo)(nil),              // 212: leonidaspb.ServiceInfo
	(*leonidaspb.PivotListener)(nil),            // 213: leonidaspb.PivotListener
	(*leonidaspb.PivotListeners)(nil),           // 214: leonidaspb.PivotListeners
	(*clientpb.PivotGraph)(nil),               // 215: clientpb.PivotGraph
	(*leonidaspb.MakeToken)(nil),                // 216: leonidaspb.MakeToken
	(*leonidaspb.EnvInfo)(nil),                  // 217: leonidaspb.EnvInfo
	(*leonidaspb.SetEnv)(nil),                   // 218: leonidaspb.SetEnv
	(*leonidaspb.UnsetEnv)(nil),                 // 219: leonidaspb.UnsetEnv
	(*clientpb.Backdoor)(nil),                 // 220: clientpb.Backdoor
	(*leonidaspb.RegistryRead)(nil),             // 221: leonidaspb.RegistryRead
	(*leonidaspb.RegistryWrite)(nil),            // 222: leonidaspb.RegistryWrite
	(*leonidaspb.RegistryCreateKey)(nil),        // 223: leonidaspb.RegistryCreateKey
	(*leonidaspb.RegistryDeleteKey)(nil),        // 224: leonidaspb.RegistryDeleteKey
	(*leonidaspb.RegistrySubKeyList)(nil),       // 225: leonidaspb.RegistrySubKeyList
	(*leonidaspb.RegistryValuesList)(nil),       // 226: leonidaspb.RegistryValuesList
	(*leonidaspb.RegistryReadHive)(nil),         // 227: leonidaspb.RegistryReadHive
	(*leonidaspb.SSHCommand)(nil),               // 228: leonidaspb.SSHCommand
	(*clientpb.DllHijack)(nil),                // 229: clientpb.DllHijack
	(*leonidaspb.GetPrivs)(nil),                 // 230: leonidaspb.GetPrivs
	(*leonidaspb.RportFwdListener)(nil),         // 231: leonidaspb.RportFwdListener
	(*leonidaspb.RportFwdListeners)(nil),        // 232: leonidaspb.RportFwdListeners
	(*leonidaspb.RegisterExtension)(nil),        // 233: leonidaspb.RegisterExtension
	(*leonidaspb.CallExtension)(nil),            // 234: leonidaspb.CallExtension
	(*leonidaspb.ListExtensions)(nil),           // 235: leonidaspb.ListExtensions
	(*leonidaspb.RegisterWasmExtension)(nil),    // 236: leonidaspb.RegisterWasmExtension
	(*leonidaspb.ListWasmExtensions)(nil),       // 237: leonidaspb.ListWasmExtensions
	(*leonidaspb.ExecWasmExtension)(nil),        // 238: leonidaspb.ExecWasmExtension
	(*leonidaspb.WGPortForward)(nil),            // 239: leonidaspb.WGPortForward
	(*leonidaspb.WGSocks)(nil),                  // 240: leonidaspb.WGSocks
	(*leonidaspb.WGTCPForwarders)(nil),          // 241: leonidaspb.WGTCPForwarders
	(*leonidaspb.WGSocksServers)(nil),           // 242: leonidaspb.WGSocksServers
	(*leonidaspb.Shell)(nil),                    // 243: leonidaspb.Shell
	(*leonidaspb.Portfwd)(nil),                  // 244: leonidaspb.Portfwd
}
var file_rpcpb_services_proto_depIdxs = []int32{
	0,   // 0: rpcpb.LeonidasRPC.GetVersion:input_type -> commonpb.Empty
	1,   // 1: rpcpb.LeonidasRPC.ClientLog:input_type -> clientpb.ClientLogData
	0,   // 2: rpcpb.LeonidasRPC.GetOperators:input_type -> commonpb.Empty
	2,   // 3: rpcpb.LeonidasRPC.Kill:input_type -> leonidaspb.KillReq
	3,   // 4: rpcpb.LeonidasRPC.Reconfigure:input_type -> leonidaspb.ReconfigureReq
	4,   // 5: rpcpb.LeonidasRPC.Rename:input_type -> clientpb.RenameReq
	0,   // 6: rpcpb.LeonidasRPC.GetSessions:input_type -> commonpb.Empty
	0,   // 7: rpcpb.LeonidasRPC.MonitorStart:input_type -> commonpb.Empty
	0,   // 8: rpcpb.LeonidasRPC.MonitorStop:input_type -> commonpb.Empty
	0,   // 9: rpcpb.LeonidasRPC.MonitorListConfig:input_type -> commonpb.Empty
	5,   // 10: rpcpb.LeonidasRPC.MonitorAddConfig:input_type -> clientpb.MonitoringProvider
	5,   // 11: rpcpb.LeonidasRPC.MonitorDelConfig:input_type -> clientpb.MonitoringProvider
	0,   // 12: rpcpb.LeonidasRPC.GetAIProviders:input_type -> commonpb.Empty
	0,   // 13: rpcpb.LeonidasRPC.GetAIConversations:input_type -> commonpb.Empty
	6,   // 14: rpcpb.LeonidasRPC.GetAIConversation:input_type -> clientpb.AIConversationReq
	7,   // 15: rpcpb.LeonidasRPC.SaveAIConversation:input_type -> clientpb.AIConversation
	6,   // 16: rpcpb.LeonidasRPC.DeleteAIConversation:input_type -> clientpb.AIConversationReq
	6,   // 17: rpcpb.LeonidasRPC.GetAIConversationMessages:input_type -> clientpb.AIConversationReq
	8,   // 18: rpcpb.LeonidasRPC.SaveAIConversationMessage:input_type -> clientpb.AIConversationMessage
	9,   // 19: rpcpb.LeonidasRPC.StartMTLSListener:input_type -> clientpb.MTLSListenerReq
	10,  // 20: rpcpb.LeonidasRPC.StartWGListener:input_type -> clientpb.WGListenerReq
	11,  // 21: rpcpb.LeonidasRPC.StartDNSListener:input_type -> clientpb.DNSListenerReq
	12,  // 22: rpcpb.LeonidasRPC.StartHTTPSListener:input_type -> clientpb.HTTPListenerReq
	12,  // 23: rpcpb.LeonidasRPC.StartHTTPListener:input_type -> clientpb.HTTPListenerReq
	0,   // 24: rpcpb.LeonidasRPC.GetBeacons:input_type -> commonpb.Empty
	13,  // 25: rpcpb.LeonidasRPC.GetBeacon:input_type -> clientpb.Beacon
	13,  // 26: rpcpb.LeonidasRPC.RmBeacon:input_type -> clientpb.Beacon
	13,  // 27: rpcpb.LeonidasRPC.GetBeaconTasks:input_type -> clientpb.Beacon
	14,  // 28: rpcpb.LeonidasRPC.GetBeaconTaskContent:input_type -> clientpb.BeaconTask
	14,  // 29: rpcpb.LeonidasRPC.CancelBeaconTask:input_type -> clientpb.BeaconTask
	15,  // 30: rpcpb.LeonidasRPC.UpdateBeaconIntegrityInformation:input_type -> clientpb.BeaconIntegrity
	0,   // 31: rpcpb.LeonidasRPC.GetJobs:input_type -> commonpb.Empty
	16,  // 32: rpcpb.LeonidasRPC.KillJob:input_type -> clientpb.KillJobReq
	17,  // 33: rpcpb.LeonidasRPC.RestartJobs:input_type -> clientpb.RestartJobReq
	18,  // 34: rpcpb.LeonidasRPC.StartTCPStagerListener:input_type -> clientpb.StagerListenerReq
	19,  // 35: rpcpb.LeonidasRPC.LootAdd:input_type -> clientpb.Loot
	19,  // 36: rpcpb.LeonidasRPC.LootRm:input_type -> clientpb.Loot
	19,  // 37: rpcpb.LeonidasRPC.LootUpdate:input_type -> clientpb.Loot
	19,  // 38: rpcpb.LeonidasRPC.LootContent:input_type -> clientpb.Loot
	0,   // 39: rpcpb.LeonidasRPC.LootAll:input_type -> commonpb.Empty
	0,   // 40: rpcpb.LeonidasRPC.Creds:input_type -> commonpb.Empty
	20,  // 41: rpcpb.LeonidasRPC.CredsAdd:input_type -> clientpb.Credentials
	20,  // 42: rpcpb.LeonidasRPC.CredsRm:input_type -> clientpb.Credentials
	20,  // 43: rpcpb.LeonidasRPC.CredsUpdate:input_type -> clientpb.Credentials
	21,  // 44: rpcpb.LeonidasRPC.GetCredByID:input_type -> clientpb.Credential
	21,  // 45: rpcpb.LeonidasRPC.GetCredsByHashType:input_type -> clientpb.Credential
	21,  // 46: rpcpb.LeonidasRPC.GetPlaintextCredsByHashType:input_type -> clientpb.Credential
	21,  // 47: rpcpb.LeonidasRPC.CredsSniffHashType:input_type -> clientpb.Credential
	0,   // 48: rpcpb.LeonidasRPC.Hosts:input_type -> commonpb.Empty
	22,  // 49: rpcpb.LeonidasRPC.Host:input_type -> clientpb.Host
	22,  // 50: rpcpb.LeonidasRPC.HostRm:input_type -> clientpb.Host
	23,  // 51: rpcpb.LeonidasRPC.HostIOCRm:input_type -> clientpb.IOC
	24,  // 52: rpcpb.LeonidasRPC.Generate:input_type -> clientpb.GenerateReq
	25,  // 53: rpcpb.LeonidasRPC.GenerateSpoofMetadata:input_type -> clientpb.GenerateSpoofMetadataReq
	26,  // 54: rpcpb.LeonidasRPC.GenerateExternal:input_type -> clientpb.ExternalGenerateReq
	27,  // 55: rpcpb.LeonidasRPC.GenerateExternalSaveBuild:input_type -> clientpb.ExternalImplantBinary
	28,  // 56: rpcpb.LeonidasRPC.GenerateExternalGetBuildConfig:input_type -> clientpb.ImplantBuild
	29,  // 57: rpcpb.LeonidasRPC.GenerateStage:input_type -> clientpb.GenerateStageReq
	30,  // 58: rpcpb.LeonidasRPC.StageImplantBuild:input_type -> clientpb.ImplantStageReq
	0,   // 59: rpcpb.LeonidasRPC.GetHTTPC2Profiles:input_type -> commonpb.Empty
	31,  // 60: rpcpb.LeonidasRPC.GetHTTPC2ProfileByName:input_type -> clientpb.C2ProfileReq
	32,  // 61: rpcpb.LeonidasRPC.SaveHTTPC2Profile:input_type -> clientpb.HTTPC2ConfigReq
	33,  // 62: rpcpb.LeonidasRPC.BuilderRegister:input_type -> clientpb.Builder
	34,  // 63: rpcpb.LeonidasRPC.BuilderTrigger:input_type -> clientpb.Event
	0,   // 64: rpcpb.LeonidasRPC.Builders:input_type -> commonpb.Empty
	35,  // 65: rpcpb.LeonidasRPC.GetCertificateInfo:input_type -> clientpb.CertificatesReq
	0,   // 66: rpcpb.LeonidasRPC.GetCertificateAuthorityInfo:input_type -> commonpb.Empty
	36,  // 67: rpcpb.LeonidasRPC.Crack:input_type -> clientpb.CrackCommand
	37,  // 68: rpcpb.LeonidasRPC.CrackstationRegister:input_type -> clientpb.Crackstation
	34,  // 69: rpcpb.LeonidasRPC.CrackstationTrigger:input_type -> clientpb.Event
	38,  // 70: rpcpb.LeonidasRPC.CrackstationBenchmark:input_type -> clientpb.CrackBenchmark
	0,   // 71: rpcpb.LeonidasRPC.Crackstations:input_type -> commonpb.Empty
	39,  // 72: rpcpb.LeonidasRPC.CrackTaskByID:input_type -> clientpb.CrackTask
	39,  // 73: rpcpb.LeonidasRPC.CrackTaskUpdate:input_type -> clientpb.CrackTask
	40,  // 74: rpcpb.LeonidasRPC.CrackFilesList:input_type -> clientpb.CrackFile
	40,  // 75: rpcpb.LeonidasRPC.CrackFileCreate:input_type -> clientpb.CrackFile
	41,  // 76: rpcpb.LeonidasRPC.CrackFileChunkUpload:input_type -> clientpb.CrackFileChunk
	41,  // 77: rpcpb.LeonidasRPC.CrackFileChunkDownload:input_type -> clientpb.CrackFileChunk
	40,  // 78: rpcpb.LeonidasRPC.CrackFileComplete:input_type -> clientpb.CrackFile
	40,  // 79: rpcpb.LeonidasRPC.CrackFileDelete:input_type -> clientpb.CrackFile
	42,  // 80: rpcpb.LeonidasRPC.Regenerate:input_type -> clientpb.RegenerateReq
	0,   // 81: rpcpb.LeonidasRPC.ImplantBuilds:input_type -> commonpb.Empty
	43,  // 82: rpcpb.LeonidasRPC.DeleteImplantBuild:input_type -> clientpb.DeleteReq
	0,   // 83: rpcpb.LeonidasRPC.Canaries:input_type -> commonpb.Empty
	0,   // 84: rpcpb.LeonidasRPC.GenerateWGClientConfig:input_type -> commonpb.Empty
	0,   // 85: rpcpb.LeonidasRPC.GenerateUniqueIP:input_type -> commonpb.Empty
	0,   // 86: rpcpb.LeonidasRPC.ImplantProfiles:input_type -> commonpb.Empty
	43,  // 87: rpcpb.LeonidasRPC.DeleteImplantProfile:input_type -> clientpb.DeleteReq
	44,  // 88: rpcpb.LeonidasRPC.SaveImplantProfile:input_type -> clientpb.ImplantProfile
	45,  // 89: rpcpb.LeonidasRPC.ShellcodeRDI:input_type -> clientpb.ShellcodeRDIReq
	0,   // 90: rpcpb.LeonidasRPC.GetCompiler:input_type -> commonpb.Empty
	46,  // 91: rpcpb.LeonidasRPC.ShellcodeEncoder:input_type -> clientpb.ShellcodeEncodeReq
	0,   // 92: rpcpb.LeonidasRPC.ShellcodeEncoderMap:input_type -> commonpb.Empty
	0,   // 93: rpcpb.LeonidasRPC.TrafficEncoderMap:input_type -> commonpb.Empty
	47,  // 94: rpcpb.LeonidasRPC.TrafficEncoderAdd:input_type -> clientpb.TrafficEncoder
	47,  // 95: rpcpb.LeonidasRPC.TrafficEncoderRm:input_type -> clientpb.TrafficEncoder
	0,   // 96: rpcpb.LeonidasRPC.Websites:input_type -> commonpb.Empty
	48,  // 97: rpcpb.LeonidasRPC.Website:input_type -> clientpb.Website
	48,  // 98: rpcpb.LeonidasRPC.WebsiteRemove:input_type -> clientpb.Website
	49,  // 99: rpcpb.LeonidasRPC.WebsiteAddContent:input_type -> clientpb.WebsiteAddContent
	49,  // 100: rpcpb.LeonidasRPC.WebsiteUpdateContent:input_type -> clientpb.WebsiteAddContent
	50,  // 101: rpcpb.LeonidasRPC.WebsiteRemoveContent:input_type -> clientpb.WebsiteRemoveContent
	51,  // 102: rpcpb.LeonidasRPC.Ping:input_type -> leonidaspb.Ping
	52,  // 103: rpcpb.LeonidasRPC.Ps:input_type -> leonidaspb.PsReq
	53,  // 104: rpcpb.LeonidasRPC.Terminate:input_type -> leonidaspb.TerminateReq
	54,  // 105: rpcpb.LeonidasRPC.Ifconfig:input_type -> leonidaspb.IfconfigReq
	55,  // 106: rpcpb.LeonidasRPC.Netstat:input_type -> leonidaspb.NetstatReq
	56,  // 107: rpcpb.LeonidasRPC.Ls:input_type -> leonidaspb.LsReq
	57,  // 108: rpcpb.LeonidasRPC.Cd:input_type -> leonidaspb.CdReq
	58,  // 109: rpcpb.LeonidasRPC.Pwd:input_type -> leonidaspb.PwdReq
	59,  // 110: rpcpb.LeonidasRPC.Mv:input_type -> leonidaspb.MvReq
	60,  // 111: rpcpb.LeonidasRPC.Cp:input_type -> leonidaspb.CpReq
	61,  // 112: rpcpb.LeonidasRPC.Rm:input_type -> leonidaspb.RmReq
	62,  // 113: rpcpb.LeonidasRPC.Mkdir:input_type -> leonidaspb.MkdirReq
	63,  // 114: rpcpb.LeonidasRPC.Download:input_type -> leonidaspb.DownloadReq
	64,  // 115: rpcpb.LeonidasRPC.Upload:input_type -> leonidaspb.UploadReq
	65,  // 116: rpcpb.LeonidasRPC.Grep:input_type -> leonidaspb.GrepReq
	66,  // 117: rpcpb.LeonidasRPC.Chmod:input_type -> leonidaspb.ChmodReq
	67,  // 118: rpcpb.LeonidasRPC.Chown:input_type -> leonidaspb.ChownReq
	68,  // 119: rpcpb.LeonidasRPC.Chtimes:input_type -> leonidaspb.ChtimesReq
	69,  // 120: rpcpb.LeonidasRPC.MemfilesList:input_type -> leonidaspb.MemfilesListReq
	70,  // 121: rpcpb.LeonidasRPC.MemfilesAdd:input_type -> leonidaspb.MemfilesAddReq
	71,  // 122: rpcpb.LeonidasRPC.MemfilesRm:input_type -> leonidaspb.MemfilesRmReq
	72,  // 123: rpcpb.LeonidasRPC.Mount:input_type -> leonidaspb.MountReq
	73,  // 124: rpcpb.LeonidasRPC.ProcessDump:input_type -> leonidaspb.ProcessDumpReq
	74,  // 125: rpcpb.LeonidasRPC.RunAs:input_type -> leonidaspb.RunAsReq
	75,  // 126: rpcpb.LeonidasRPC.Impersonate:input_type -> leonidaspb.ImpersonateReq
	76,  // 127: rpcpb.LeonidasRPC.RevToSelf:input_type -> leonidaspb.RevToSelfReq
	77,  // 128: rpcpb.LeonidasRPC.GetSystem:input_type -> clientpb.GetSystemReq
	78,  // 129: rpcpb.LeonidasRPC.Task:input_type -> leonidaspb.TaskReq
	79,  // 130: rpcpb.LeonidasRPC.Msf:input_type -> clientpb.MSFReq
	80,  // 131: rpcpb.LeonidasRPC.MsfRemote:input_type -> clientpb.MSFRemoteReq
	81,  // 132: rpcpb.LeonidasRPC.ExecuteAssembly:input_type -> leonidaspb.ExecuteAssemblyReq
	82,  // 133: rpcpb.LeonidasRPC.Migrate:input_type -> clientpb.MigrateReq
	83,  // 134: rpcpb.LeonidasRPC.Execute:input_type -> leonidaspb.ExecuteReq
	84,  // 135: rpcpb.LeonidasRPC.ExecuteWindows:input_type -> leonidaspb.ExecuteWindowsReq
	85,  // 136: rpcpb.LeonidasRPC.ExecuteChildren:input_type -> leonidaspb.ExecuteChildrenReq
	86,  // 137: rpcpb.LeonidasRPC.Sideload:input_type -> leonidaspb.SideloadReq
	87,  // 138: rpcpb.LeonidasRPC.SpawnDll:input_type -> leonidaspb.InvokeSpawnDllReq
	88,  // 139: rpcpb.LeonidasRPC.Screenshot:input_type -> leonidaspb.ScreenshotReq
	89,  // 140: rpcpb.LeonidasRPC.CurrentTokenOwner:input_type -> leonidaspb.CurrentTokenOwnerReq
	90,  // 141: rpcpb.LeonidasRPC.Services:input_type -> leonidaspb.ServicesReq
	91,  // 142: rpcpb.LeonidasRPC.ServiceDetail:input_type -> leonidaspb.ServiceDetailReq
	92,  // 143: rpcpb.LeonidasRPC.StartServiceByName:input_type -> leonidaspb.StartServiceByNameReq
	93,  // 144: rpcpb.LeonidasRPC.PivotStartListener:input_type -> leonidaspb.PivotStartListenerReq
	94,  // 145: rpcpb.LeonidasRPC.PivotStopListener:input_type -> leonidaspb.PivotStopListenerReq
	95,  // 146: rpcpb.LeonidasRPC.PivotSessionListeners:input_type -> leonidaspb.PivotListenersReq
	0,   // 147: rpcpb.LeonidasRPC.PivotGraph:input_type -> commonpb.Empty
	96,  // 148: rpcpb.LeonidasRPC.StartService:input_type -> leonidaspb.StartServiceReq
	97,  // 149: rpcpb.LeonidasRPC.StopService:input_type -> leonidaspb.StopServiceReq
	98,  // 150: rpcpb.LeonidasRPC.RemoveService:input_type -> leonidaspb.RemoveServiceReq
	99,  // 151: rpcpb.LeonidasRPC.MakeToken:input_type -> leonidaspb.MakeTokenReq
	100, // 152: rpcpb.LeonidasRPC.GetEnv:input_type -> leonidaspb.EnvReq
	101, // 153: rpcpb.LeonidasRPC.SetEnv:input_type -> leonidaspb.SetEnvReq
	102, // 154: rpcpb.LeonidasRPC.UnsetEnv:input_type -> leonidaspb.UnsetEnvReq
	103, // 155: rpcpb.LeonidasRPC.Backdoor:input_type -> clientpb.BackdoorReq
	104, // 156: rpcpb.LeonidasRPC.RegistryRead:input_type -> leonidaspb.RegistryReadReq
	105, // 157: rpcpb.LeonidasRPC.RegistryWrite:input_type -> leonidaspb.RegistryWriteReq
	106, // 158: rpcpb.LeonidasRPC.RegistryCreateKey:input_type -> leonidaspb.RegistryCreateKeyReq
	107, // 159: rpcpb.LeonidasRPC.RegistryDeleteKey:input_type -> leonidaspb.RegistryDeleteKeyReq
	108, // 160: rpcpb.LeonidasRPC.RegistryListSubKeys:input_type -> leonidaspb.RegistrySubKeyListReq
	109, // 161: rpcpb.LeonidasRPC.RegistryListValues:input_type -> leonidaspb.RegistryListValuesReq
	110, // 162: rpcpb.LeonidasRPC.RegistryReadHive:input_type -> leonidaspb.RegistryReadHiveReq
	111, // 163: rpcpb.LeonidasRPC.RunSSHCommand:input_type -> leonidaspb.SSHCommandReq
	112, // 164: rpcpb.LeonidasRPC.HijackDLL:input_type -> clientpb.DllHijackReq
	113, // 165: rpcpb.LeonidasRPC.GetPrivs:input_type -> leonidaspb.GetPrivsReq
	114, // 166: rpcpb.LeonidasRPC.StartRportFwdListener:input_type -> leonidaspb.RportFwdStartListenerReq
	115, // 167: rpcpb.LeonidasRPC.GetRportFwdListeners:input_type -> leonidaspb.RportFwdListenersReq
	116, // 168: rpcpb.LeonidasRPC.StopRportFwdListener:input_type -> leonidaspb.RportFwdStopListenerReq
	117, // 169: rpcpb.LeonidasRPC.OpenSession:input_type -> leonidaspb.OpenSession
	118, // 170: rpcpb.LeonidasRPC.CloseSession:input_type -> leonidaspb.CloseSession
	119, // 171: rpcpb.LeonidasRPC.RegisterExtension:input_type -> leonidaspb.RegisterExtensionReq
	120, // 172: rpcpb.LeonidasRPC.CallExtension:input_type -> leonidaspb.CallExtensionReq
	121, // 173: rpcpb.LeonidasRPC.ListExtensions:input_type -> leonidaspb.ListExtensionsReq
	122, // 174: rpcpb.LeonidasRPC.RegisterWasmExtension:input_type -> leonidaspb.RegisterWasmExtensionReq
	123, // 175: rpcpb.LeonidasRPC.ListWasmExtensions:input_type -> leonidaspb.ListWasmExtensionsReq
	124, // 176: rpcpb.LeonidasRPC.ExecWasmExtension:input_type -> leonidaspb.ExecWasmExtensionReq
	125, // 177: rpcpb.LeonidasRPC.WGStartPortForward:input_type -> leonidaspb.WGPortForwardStartReq
	126, // 178: rpcpb.LeonidasRPC.WGStopPortForward:input_type -> leonidaspb.WGPortForwardStopReq
	127, // 179: rpcpb.LeonidasRPC.WGStartSocks:input_type -> leonidaspb.WGSocksStartReq
	128, // 180: rpcpb.LeonidasRPC.WGStopSocks:input_type -> leonidaspb.WGSocksStopReq
	129, // 181: rpcpb.LeonidasRPC.WGListForwarders:input_type -> leonidaspb.WGTCPForwardersReq
	130, // 182: rpcpb.LeonidasRPC.WGListSocksServers:input_type -> leonidaspb.WGSocksServersReq
	131, // 183: rpcpb.LeonidasRPC.Shell:input_type -> leonidaspb.ShellReq
	132, // 184: rpcpb.LeonidasRPC.ShellResize:input_type -> leonidaspb.ShellResizeReq
	133, // 185: rpcpb.LeonidasRPC.Portfwd:input_type -> leonidaspb.PortfwdReq
	134, // 186: rpcpb.LeonidasRPC.CreateSocks:input_type -> leonidaspb.Socks
	134, // 187: rpcpb.LeonidasRPC.CloseSocks:input_type -> leonidaspb.Socks
	135, // 188: rpcpb.LeonidasRPC.SocksProxy:input_type -> leonidaspb.SocksData
	136, // 189: rpcpb.LeonidasRPC.CreateTunnel:input_type -> leonidaspb.Tunnel
	136, // 190: rpcpb.LeonidasRPC.CloseTunnel:input_type -> leonidaspb.Tunnel
	137, // 191: rpcpb.LeonidasRPC.TunnelData:input_type -> leonidaspb.TunnelData
	0,   // 192: rpcpb.LeonidasRPC.Events:input_type -> commonpb.Empty
	138, // 193: rpcpb.LeonidasRPC.GetVersion:output_type -> clientpb.Version
	0,   // 194: rpcpb.LeonidasRPC.ClientLog:output_type -> commonpb.Empty
	139, // 195: rpcpb.LeonidasRPC.GetOperators:output_type -> clientpb.Operators
	0,   // 196: rpcpb.LeonidasRPC.Kill:output_type -> commonpb.Empty
	140, // 197: rpcpb.LeonidasRPC.Reconfigure:output_type -> leonidaspb.Reconfigure
	0,   // 198: rpcpb.LeonidasRPC.Rename:output_type -> commonpb.Empty
	141, // 199: rpcpb.LeonidasRPC.GetSessions:output_type -> clientpb.Sessions
	142, // 200: rpcpb.LeonidasRPC.MonitorStart:output_type -> commonpb.Response
	0,   // 201: rpcpb.LeonidasRPC.MonitorStop:output_type -> commonpb.Empty
	143, // 202: rpcpb.LeonidasRPC.MonitorListConfig:output_type -> clientpb.MonitoringProviders
	142, // 203: rpcpb.LeonidasRPC.MonitorAddConfig:output_type -> commonpb.Response
	142, // 204: rpcpb.LeonidasRPC.MonitorDelConfig:output_type -> commonpb.Response
	144, // 205: rpcpb.LeonidasRPC.GetAIProviders:output_type -> clientpb.AIProviderConfigs
	145, // 206: rpcpb.LeonidasRPC.GetAIConversations:output_type -> clientpb.AIConversations
	7,   // 207: rpcpb.LeonidasRPC.GetAIConversation:output_type -> clientpb.AIConversation
	7,   // 208: rpcpb.LeonidasRPC.SaveAIConversation:output_type -> clientpb.AIConversation
	0,   // 209: rpcpb.LeonidasRPC.DeleteAIConversation:output_type -> commonpb.Empty
	146, // 210: rpcpb.LeonidasRPC.GetAIConversationMessages:output_type -> clientpb.AIConversationMessages
	8,   // 211: rpcpb.LeonidasRPC.SaveAIConversationMessage:output_type -> clientpb.AIConversationMessage
	147, // 212: rpcpb.LeonidasRPC.StartMTLSListener:output_type -> clientpb.ListenerJob
	147, // 213: rpcpb.LeonidasRPC.StartWGListener:output_type -> clientpb.ListenerJob
	147, // 214: rpcpb.LeonidasRPC.StartDNSListener:output_type -> clientpb.ListenerJob
	147, // 215: rpcpb.LeonidasRPC.StartHTTPSListener:output_type -> clientpb.ListenerJob
	147, // 216: rpcpb.LeonidasRPC.StartHTTPListener:output_type -> clientpb.ListenerJob
	148, // 217: rpcpb.LeonidasRPC.GetBeacons:output_type -> clientpb.Beacons
	13,  // 218: rpcpb.LeonidasRPC.GetBeacon:output_type -> clientpb.Beacon
	0,   // 219: rpcpb.LeonidasRPC.RmBeacon:output_type -> commonpb.Empty
	149, // 220: rpcpb.LeonidasRPC.GetBeaconTasks:output_type -> clientpb.BeaconTasks
	14,  // 221: rpcpb.LeonidasRPC.GetBeaconTaskContent:output_type -> clientpb.BeaconTask
	14,  // 222: rpcpb.LeonidasRPC.CancelBeaconTask:output_type -> clientpb.BeaconTask
	0,   // 223: rpcpb.LeonidasRPC.UpdateBeaconIntegrityInformation:output_type -> commonpb.Empty
	150, // 224: rpcpb.LeonidasRPC.GetJobs:output_type -> clientpb.Jobs
	151, // 225: rpcpb.LeonidasRPC.KillJob:output_type -> clientpb.KillJob
	0,   // 226: rpcpb.LeonidasRPC.RestartJobs:output_type -> commonpb.Empty
	152, // 227: rpcpb.LeonidasRPC.StartTCPStagerListener:output_type -> clientpb.StagerListener
	19,  // 228: rpcpb.LeonidasRPC.LootAdd:output_type -> clientpb.Loot
	0,   // 229: rpcpb.LeonidasRPC.LootRm:output_type -> commonpb.Empty
	19,  // 230: rpcpb.LeonidasRPC.LootUpdate:output_type -> clientpb.Loot
	19,  // 231: rpcpb.LeonidasRPC.LootContent:output_type -> clientpb.Loot
	153, // 232: rpcpb.LeonidasRPC.LootAll:output_type -> clientpb.AllLoot
	20,  // 233: rpcpb.LeonidasRPC.Creds:output_type -> clientpb.Credentials
	0,   // 234: rpcpb.LeonidasRPC.CredsAdd:output_type -> commonpb.Empty
	0,   // 235: rpcpb.LeonidasRPC.CredsRm:output_type -> commonpb.Empty
	0,   // 236: rpcpb.LeonidasRPC.CredsUpdate:output_type -> commonpb.Empty
	21,  // 237: rpcpb.LeonidasRPC.GetCredByID:output_type -> clientpb.Credential
	20,  // 238: rpcpb.LeonidasRPC.GetCredsByHashType:output_type -> clientpb.Credentials
	20,  // 239: rpcpb.LeonidasRPC.GetPlaintextCredsByHashType:output_type -> clientpb.Credentials
	21,  // 240: rpcpb.LeonidasRPC.CredsSniffHashType:output_type -> clientpb.Credential
	154, // 241: rpcpb.LeonidasRPC.Hosts:output_type -> clientpb.AllHosts
	22,  // 242: rpcpb.LeonidasRPC.Host:output_type -> clientpb.Host
	0,   // 243: rpcpb.LeonidasRPC.HostRm:output_type -> commonpb.Empty
	0,   // 244: rpcpb.LeonidasRPC.HostIOCRm:output_type -> commonpb.Empty
	155, // 245: rpcpb.LeonidasRPC.Generate:output_type -> clientpb.Generate
	0,   // 246: rpcpb.LeonidasRPC.GenerateSpoofMetadata:output_type -> commonpb.Empty
	156, // 247: rpcpb.LeonidasRPC.GenerateExternal:output_type -> clientpb.ExternalImplantConfig
	0,   // 248: rpcpb.LeonidasRPC.GenerateExternalSaveBuild:output_type -> commonpb.Empty
	156, // 249: rpcpb.LeonidasRPC.GenerateExternalGetBuildConfig:output_type -> clientpb.ExternalImplantConfig
	155, // 250: rpcpb.LeonidasRPC.GenerateStage:output_type -> clientpb.Generate
	0,   // 251: rpcpb.LeonidasRPC.StageImplantBuild:output_type -> commonpb.Empty
	157, // 252: rpcpb.LeonidasRPC.GetHTTPC2Profiles:output_type -> clientpb.HTTPC2Configs
	158, // 253: rpcpb.LeonidasRPC.GetHTTPC2ProfileByName:output_type -> clientpb.HTTPC2Config
	0,   // 254: rpcpb.LeonidasRPC.SaveHTTPC2Profile:output_type -> commonpb.Empty
	34,  // 255: rpcpb.LeonidasRPC.BuilderRegister:output_type -> clientpb.Event
	0,   // 256: rpcpb.LeonidasRPC.BuilderTrigger:output_type -> commonpb.Empty
	159, // 257: rpcpb.LeonidasRPC.Builders:output_type -> clientpb.Builders
	160, // 258: rpcpb.LeonidasRPC.GetCertificateInfo:output_type -> clientpb.CertificateInfo
	161, // 259: rpcpb.LeonidasRPC.GetCertificateAuthorityInfo:output_type -> clientpb.CertificateAuthorityInfo
	162, // 260: rpcpb.LeonidasRPC.Crack:output_type -> clientpb.CrackResponse
	34,  // 261: rpcpb.LeonidasRPC.CrackstationRegister:output_type -> clientpb.Event
	0,   // 262: rpcpb.LeonidasRPC.CrackstationTrigger:output_type -> commonpb.Empty
	0,   // 263: rpcpb.LeonidasRPC.CrackstationBenchmark:output_type -> commonpb.Empty
	163, // 264: rpcpb.LeonidasRPC.Crackstations:output_type -> clientpb.Crackstations
	39,  // 265: rpcpb.LeonidasRPC.CrackTaskByID:output_type -> clientpb.CrackTask
	0,   // 266: rpcpb.LeonidasRPC.CrackTaskUpdate:output_type -> commonpb.Empty
	164, // 267: rpcpb.LeonidasRPC.CrackFilesList:output_type -> clientpb.CrackFiles
	40,  // 268: rpcpb.LeonidasRPC.CrackFileCreate:output_type -> clientpb.CrackFile
	0,   // 269: rpcpb.LeonidasRPC.CrackFileChunkUpload:output_type -> commonpb.Empty
	41,  // 270: rpcpb.LeonidasRPC.CrackFileChunkDownload:output_type -> clientpb.CrackFileChunk
	0,   // 271: rpcpb.LeonidasRPC.CrackFileComplete:output_type -> commonpb.Empty
	0,   // 272: rpcpb.LeonidasRPC.CrackFileDelete:output_type -> commonpb.Empty
	155, // 273: rpcpb.LeonidasRPC.Regenerate:output_type -> clientpb.Generate
	165, // 274: rpcpb.LeonidasRPC.ImplantBuilds:output_type -> clientpb.ImplantBuilds
	0,   // 275: rpcpb.LeonidasRPC.DeleteImplantBuild:output_type -> commonpb.Empty
	166, // 276: rpcpb.LeonidasRPC.Canaries:output_type -> clientpb.Canaries
	167, // 277: rpcpb.LeonidasRPC.GenerateWGClientConfig:output_type -> clientpb.WGClientConfig
	168, // 278: rpcpb.LeonidasRPC.GenerateUniqueIP:output_type -> clientpb.UniqueWGIP
	169, // 279: rpcpb.LeonidasRPC.ImplantProfiles:output_type -> clientpb.ImplantProfiles
	0,   // 280: rpcpb.LeonidasRPC.DeleteImplantProfile:output_type -> commonpb.Empty
	44,  // 281: rpcpb.LeonidasRPC.SaveImplantProfile:output_type -> clientpb.ImplantProfile
	170, // 282: rpcpb.LeonidasRPC.ShellcodeRDI:output_type -> clientpb.ShellcodeRDI
	171, // 283: rpcpb.LeonidasRPC.GetCompiler:output_type -> clientpb.Compiler
	172, // 284: rpcpb.LeonidasRPC.ShellcodeEncoder:output_type -> clientpb.ShellcodeEncode
	173, // 285: rpcpb.LeonidasRPC.ShellcodeEncoderMap:output_type -> clientpb.ShellcodeEncoderMap
	174, // 286: rpcpb.LeonidasRPC.TrafficEncoderMap:output_type -> clientpb.TrafficEncoderMap
	175, // 287: rpcpb.LeonidasRPC.TrafficEncoderAdd:output_type -> clientpb.TrafficEncoderTests
	0,   // 288: rpcpb.LeonidasRPC.TrafficEncoderRm:output_type -> commonpb.Empty
	176, // 289: rpcpb.LeonidasRPC.Websites:output_type -> clientpb.Websites
	48,  // 290: rpcpb.LeonidasRPC.Website:output_type -> clientpb.Website
	0,   // 291: rpcpb.LeonidasRPC.WebsiteRemove:output_type -> commonpb.Empty
	48,  // 292: rpcpb.LeonidasRPC.WebsiteAddContent:output_type -> clientpb.Website
	48,  // 293: rpcpb.LeonidasRPC.WebsiteUpdateContent:output_type -> clientpb.Website
	48,  // 294: rpcpb.LeonidasRPC.WebsiteRemoveContent:output_type -> clientpb.Website
	51,  // 295: rpcpb.LeonidasRPC.Ping:output_type -> leonidaspb.Ping
	177, // 296: rpcpb.LeonidasRPC.Ps:output_type -> leonidaspb.Ps
	178, // 297: rpcpb.LeonidasRPC.Terminate:output_type -> leonidaspb.Terminate
	179, // 298: rpcpb.LeonidasRPC.Ifconfig:output_type -> leonidaspb.Ifconfig
	180, // 299: rpcpb.LeonidasRPC.Netstat:output_type -> leonidaspb.Netstat
	181, // 300: rpcpb.LeonidasRPC.Ls:output_type -> leonidaspb.Ls
	182, // 301: rpcpb.LeonidasRPC.Cd:output_type -> leonidaspb.Pwd
	182, // 302: rpcpb.LeonidasRPC.Pwd:output_type -> leonidaspb.Pwd
	183, // 303: rpcpb.LeonidasRPC.Mv:output_type -> leonidaspb.Mv
	184, // 304: rpcpb.LeonidasRPC.Cp:output_type -> leonidaspb.Cp
	185, // 305: rpcpb.LeonidasRPC.Rm:output_type -> leonidaspb.Rm
	186, // 306: rpcpb.LeonidasRPC.Mkdir:output_type -> leonidaspb.Mkdir
	187, // 307: rpcpb.LeonidasRPC.Download:output_type -> leonidaspb.Download
	188, // 308: rpcpb.LeonidasRPC.Upload:output_type -> leonidaspb.Upload
	189, // 309: rpcpb.LeonidasRPC.Grep:output_type -> leonidaspb.Grep
	190, // 310: rpcpb.LeonidasRPC.Chmod:output_type -> leonidaspb.Chmod
	191, // 311: rpcpb.LeonidasRPC.Chown:output_type -> leonidaspb.Chown
	192, // 312: rpcpb.LeonidasRPC.Chtimes:output_type -> leonidaspb.Chtimes
	181, // 313: rpcpb.LeonidasRPC.MemfilesList:output_type -> leonidaspb.Ls
	193, // 314: rpcpb.LeonidasRPC.MemfilesAdd:output_type -> leonidaspb.MemfilesAdd
	194, // 315: rpcpb.LeonidasRPC.MemfilesRm:output_type -> leonidaspb.MemfilesRm
	195, // 316: rpcpb.LeonidasRPC.Mount:output_type -> leonidaspb.Mount
	196, // 317: rpcpb.LeonidasRPC.ProcessDump:output_type -> leonidaspb.ProcessDump
	197, // 318: rpcpb.LeonidasRPC.RunAs:output_type -> leonidaspb.RunAs
	198, // 319: rpcpb.LeonidasRPC.Impersonate:output_type -> leonidaspb.Impersonate
	199, // 320: rpcpb.LeonidasRPC.RevToSelf:output_type -> leonidaspb.RevToSelf
	200, // 321: rpcpb.LeonidasRPC.GetSystem:output_type -> leonidaspb.GetSystem
	201, // 322: rpcpb.LeonidasRPC.Task:output_type -> leonidaspb.Task
	201, // 323: rpcpb.LeonidasRPC.Msf:output_type -> leonidaspb.Task
	201, // 324: rpcpb.LeonidasRPC.MsfRemote:output_type -> leonidaspb.Task
	202, // 325: rpcpb.LeonidasRPC.ExecuteAssembly:output_type -> leonidaspb.ExecuteAssembly
	203, // 326: rpcpb.LeonidasRPC.Migrate:output_type -> leonidaspb.Migrate
	204, // 327: rpcpb.LeonidasRPC.Execute:output_type -> leonidaspb.Execute
	204, // 328: rpcpb.LeonidasRPC.ExecuteWindows:output_type -> leonidaspb.Execute
	205, // 329: rpcpb.LeonidasRPC.ExecuteChildren:output_type -> leonidaspb.ExecuteChildren
	206, // 330: rpcpb.LeonidasRPC.Sideload:output_type -> leonidaspb.Sideload
	207, // 331: rpcpb.LeonidasRPC.SpawnDll:output_type -> leonidaspb.SpawnDll
	208, // 332: rpcpb.LeonidasRPC.Screenshot:output_type -> leonidaspb.Screenshot
	209, // 333: rpcpb.LeonidasRPC.CurrentTokenOwner:output_type -> leonidaspb.CurrentTokenOwner
	210, // 334: rpcpb.LeonidasRPC.Services:output_type -> leonidaspb.Services
	211, // 335: rpcpb.LeonidasRPC.ServiceDetail:output_type -> leonidaspb.ServiceDetail
	212, // 336: rpcpb.LeonidasRPC.StartServiceByName:output_type -> leonidaspb.ServiceInfo
	213, // 337: rpcpb.LeonidasRPC.PivotStartListener:output_type -> leonidaspb.PivotListener
	0,   // 338: rpcpb.LeonidasRPC.PivotStopListener:output_type -> commonpb.Empty
	214, // 339: rpcpb.LeonidasRPC.PivotSessionListeners:output_type -> leonidaspb.PivotListeners
	215, // 340: rpcpb.LeonidasRPC.PivotGraph:output_type -> clientpb.PivotGraph
	212, // 341: rpcpb.LeonidasRPC.StartService:output_type -> leonidaspb.ServiceInfo
	212, // 342: rpcpb.LeonidasRPC.StopService:output_type -> leonidaspb.ServiceInfo
	212, // 343: rpcpb.LeonidasRPC.RemoveService:output_type -> leonidaspb.ServiceInfo
	216, // 344: rpcpb.LeonidasRPC.MakeToken:output_type -> leonidaspb.MakeToken
	217, // 345: rpcpb.LeonidasRPC.GetEnv:output_type -> leonidaspb.EnvInfo
	218, // 346: rpcpb.LeonidasRPC.SetEnv:output_type -> leonidaspb.SetEnv
	219, // 347: rpcpb.LeonidasRPC.UnsetEnv:output_type -> leonidaspb.UnsetEnv
	220, // 348: rpcpb.LeonidasRPC.Backdoor:output_type -> clientpb.Backdoor
	221, // 349: rpcpb.LeonidasRPC.RegistryRead:output_type -> leonidaspb.RegistryRead
	222, // 350: rpcpb.LeonidasRPC.RegistryWrite:output_type -> leonidaspb.RegistryWrite
	223, // 351: rpcpb.LeonidasRPC.RegistryCreateKey:output_type -> leonidaspb.RegistryCreateKey
	224, // 352: rpcpb.LeonidasRPC.RegistryDeleteKey:output_type -> leonidaspb.RegistryDeleteKey
	225, // 353: rpcpb.LeonidasRPC.RegistryListSubKeys:output_type -> leonidaspb.RegistrySubKeyList
	226, // 354: rpcpb.LeonidasRPC.RegistryListValues:output_type -> leonidaspb.RegistryValuesList
	227, // 355: rpcpb.LeonidasRPC.RegistryReadHive:output_type -> leonidaspb.RegistryReadHive
	228, // 356: rpcpb.LeonidasRPC.RunSSHCommand:output_type -> leonidaspb.SSHCommand
	229, // 357: rpcpb.LeonidasRPC.HijackDLL:output_type -> clientpb.DllHijack
	230, // 358: rpcpb.LeonidasRPC.GetPrivs:output_type -> leonidaspb.GetPrivs
	231, // 359: rpcpb.LeonidasRPC.StartRportFwdListener:output_type -> leonidaspb.RportFwdListener
	232, // 360: rpcpb.LeonidasRPC.GetRportFwdListeners:output_type -> leonidaspb.RportFwdListeners
	231, // 361: rpcpb.LeonidasRPC.StopRportFwdListener:output_type -> leonidaspb.RportFwdListener
	117, // 362: rpcpb.LeonidasRPC.OpenSession:output_type -> leonidaspb.OpenSession
	0,   // 363: rpcpb.LeonidasRPC.CloseSession:output_type -> commonpb.Empty
	233, // 364: rpcpb.LeonidasRPC.RegisterExtension:output_type -> leonidaspb.RegisterExtension
	234, // 365: rpcpb.LeonidasRPC.CallExtension:output_type -> leonidaspb.CallExtension
	235, // 366: rpcpb.LeonidasRPC.ListExtensions:output_type -> leonidaspb.ListExtensions
	236, // 367: rpcpb.LeonidasRPC.RegisterWasmExtension:output_type -> leonidaspb.RegisterWasmExtension
	237, // 368: rpcpb.LeonidasRPC.ListWasmExtensions:output_type -> leonidaspb.ListWasmExtensions
	238, // 369: rpcpb.LeonidasRPC.ExecWasmExtension:output_type -> leonidaspb.ExecWasmExtension
	239, // 370: rpcpb.LeonidasRPC.WGStartPortForward:output_type -> leonidaspb.WGPortForward
	239, // 371: rpcpb.LeonidasRPC.WGStopPortForward:output_type -> leonidaspb.WGPortForward
	240, // 372: rpcpb.LeonidasRPC.WGStartSocks:output_type -> leonidaspb.WGSocks
	240, // 373: rpcpb.LeonidasRPC.WGStopSocks:output_type -> leonidaspb.WGSocks
	241, // 374: rpcpb.LeonidasRPC.WGListForwarders:output_type -> leonidaspb.WGTCPForwarders
	242, // 375: rpcpb.LeonidasRPC.WGListSocksServers:output_type -> leonidaspb.WGSocksServers
	243, // 376: rpcpb.LeonidasRPC.Shell:output_type -> leonidaspb.Shell
	0,   // 377: rpcpb.LeonidasRPC.ShellResize:output_type -> commonpb.Empty
	244, // 378: rpcpb.LeonidasRPC.Portfwd:output_type -> leonidaspb.Portfwd
	134, // 379: rpcpb.LeonidasRPC.CreateSocks:output_type -> leonidaspb.Socks
	0,   // 380: rpcpb.LeonidasRPC.CloseSocks:output_type -> commonpb.Empty
	135, // 381: rpcpb.LeonidasRPC.SocksProxy:output_type -> leonidaspb.SocksData
	136, // 382: rpcpb.LeonidasRPC.CreateTunnel:output_type -> leonidaspb.Tunnel
	0,   // 383: rpcpb.LeonidasRPC.CloseTunnel:output_type -> commonpb.Empty
	137, // 384: rpcpb.LeonidasRPC.TunnelData:output_type -> leonidaspb.TunnelData
	34,  // 385: rpcpb.LeonidasRPC.Events:output_type -> clientpb.Event
	193, // [193:386] is the sub-list for method output_type
	0,   // [0:193] is the sub-list for method input_type
	0,   // [0:0] is the sub-list for extension type_name
	0,   // [0:0] is the sub-list for extension extendee
	0,   // [0:0] is the sub-list for field type_name
}

func init() { file_rpcpb_services_proto_init() }
func file_rpcpb_services_proto_init() {
	if File_rpcpb_services_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpcpb_services_proto_rawDesc), len(file_rpcpb_services_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpcpb_services_proto_goTypes,
		DependencyIndexes: file_rpcpb_services_proto_depIdxs,
	}.Build()
	File_rpcpb_services_proto = out.File
	file_rpcpb_services_proto_goTypes = nil
	file_rpcpb_services_proto_depIdxs = nil
}
